# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Union, Optional
from datetime import datetime
from typing_extensions import Literal, Annotated, TypeAlias

from pydantic import Field as FieldInfo

from .._utils import PropertyInfo
from .._models import BaseModel
from .any_type import AnyType
from .error_event import ErrorEvent
from .inbound_email_event import InboundEmailEvent

__all__ = [
    "Call",
    "Output",
    "OutputTransformEvent",
    "OutputTransformEventCorrectedContent",
    "OutputTransformEventCorrectedContentOutput",
    "OutputTransformEventInput",
    "OutputTransformEventMetadata",
    "OutputTransformEventMetrics",
    "OutputTransformEventMetricsDifference",
    "OutputTransformEventMetricsMetrics",
    "OutputExtractEvent",
    "OutputExtractEventCorrectedContent",
    "OutputExtractEventCorrectedContentOutput",
    "OutputExtractEventInput",
    "OutputExtractEventMetadata",
    "OutputRouteEvent",
    "OutputRouteEventMetadata",
    "OutputClassifyEvent",
    "OutputClassifyEventMetadata",
    "OutputSplitCollectionEvent",
    "OutputSplitCollectionEventPrintPageOutput",
    "OutputSplitCollectionEventPrintPageOutputItem",
    "OutputSplitCollectionEventSemanticPageOutput",
    "OutputSplitCollectionEventSemanticPageOutputItem",
    "OutputSplitCollectionEventMetadata",
    "OutputSplitItemEvent",
    "OutputSplitItemEventMetadata",
    "OutputSplitItemEventPrintPageOutput",
    "OutputSplitItemEventSemanticPageOutput",
    "OutputJoinEvent",
    "OutputJoinEventItem",
    "OutputJoinEventMetadata",
    "OutputEnrichEvent",
    "OutputEnrichEventMetadata",
    "OutputCollectionProcessingEvent",
    "OutputCollectionProcessingEventMetadata",
    "OutputSendEvent",
    "OutputSendEventGoogleDriveOutput",
    "OutputSendEventMetadata",
    "OutputSendEventS3Output",
    "OutputSendEventWebhookOutput",
    "Input",
    "InputBatchFiles",
    "InputBatchFilesInput",
    "InputSingleFile",
]


class OutputTransformEventCorrectedContentOutput(BaseModel):
    output: Optional[List[Optional[AnyType]]] = None


OutputTransformEventCorrectedContent: TypeAlias = Union[
    OutputTransformEventCorrectedContentOutput, List[object], str, float, bool, object, None
]


class OutputTransformEventInput(BaseModel):
    input_content: Optional[str] = FieldInfo(alias="inputContent", default=None)

    input_type: Optional[str] = FieldInfo(alias="inputType", default=None)

    json_input_content: Optional[object] = FieldInfo(alias="jsonInputContent", default=None)

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)


class OutputTransformEventMetadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class OutputTransformEventMetricsDifference(BaseModel):
    category: Optional[str] = None

    corrected_val: Optional[object] = FieldInfo(alias="correctedVal", default=None)

    extracted_val: Optional[object] = FieldInfo(alias="extractedVal", default=None)

    json_pointer: Optional[str] = FieldInfo(alias="jsonPointer", default=None)


class OutputTransformEventMetricsMetrics(BaseModel):
    accuracy: Optional[float] = None

    f1_score: Optional[float] = FieldInfo(alias="f1Score", default=None)

    precision: Optional[float] = None

    recall: Optional[float] = None


class OutputTransformEventMetrics(BaseModel):
    """Accuracy, precision, recall, and F1 score when corrected JSON is provided."""

    differences: Optional[List[OutputTransformEventMetricsDifference]] = None

    metrics: Optional[OutputTransformEventMetricsMetrics] = None


class OutputTransformEvent(BaseModel):
    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    function_id: str = FieldInfo(alias="functionID")
    """Unique identifier of function that this event is associated with."""

    function_name: str = FieldInfo(alias="functionName")
    """Unique name of function that this event is associated with."""

    item_count: int = FieldInfo(alias="itemCount")
    """The number of items that were transformed.

    Used for batch transformations to indicate how many items were transformed.
    """

    item_offset: int = FieldInfo(alias="itemOffset")
    """The offset of the first item that was transformed.

    Used for batch transformations to indicate which item in the batch this event
    corresponds to.
    """

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    transformed_content: object = FieldInfo(alias="transformedContent")
    """The transformed content of the input.

    The structure of this object is defined by the function configuration.
    """

    avg_confidence: Optional[float] = FieldInfo(alias="avgConfidence", default=None)
    """Average confidence score across all extracted fields, in the range [0, 1]."""

    call_id: Optional[str] = FieldInfo(alias="callID", default=None)
    """Unique identifier of workflow call that this event is associated with."""

    corrected_content: Optional[OutputTransformEventCorrectedContent] = FieldInfo(
        alias="correctedContent", default=None
    )
    """Corrected feedback provided for fine-tuning purposes."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    event_type: Optional[Literal["transform"]] = FieldInfo(alias="eventType", default=None)

    field_confidences: Optional[object] = FieldInfo(alias="fieldConfidences", default=None)
    """Per-field confidence scores.

    A JSON object mapping RFC 6901 JSON Pointer paths (e.g. `"/invoiceNumber"`) to
    float values in the range [0, 1] indicating the model's confidence in each
    extracted field value.
    """

    function_call_id: Optional[str] = FieldInfo(alias="functionCallID", default=None)
    """Unique identifier of function call that this event is associated with."""

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    function_version_num: Optional[int] = FieldInfo(alias="functionVersionNum", default=None)
    """Version number of function that this event is associated with."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    inputs: Optional[List[OutputTransformEventInput]] = None
    """Array of transformation inputs with their types and S3 URLs."""

    input_type: Optional[
        Literal[
            "csv",
            "docx",
            "email",
            "heic",
            "html",
            "jpeg",
            "json",
            "heif",
            "m4a",
            "mp3",
            "pdf",
            "png",
            "text",
            "wav",
            "webp",
            "xls",
            "xlsx",
            "xml",
        ]
    ] = FieldInfo(alias="inputType", default=None)
    """The input type of the content you're sending for transformation."""

    invalid_properties: Optional[List[str]] = FieldInfo(alias="invalidProperties", default=None)
    """List of properties that were invalid in the input."""

    is_regression: Optional[bool] = FieldInfo(alias="isRegression", default=None)
    """Indicates whether this transformation was created as part of a regression test."""

    last_publish_error_at: Optional[str] = FieldInfo(alias="lastPublishErrorAt", default=None)
    """
    Last timestamp indicating when the transform was published via webhook and
    received a non-200 response. Set to `null` on a subsequent retry if the webhook
    service receives a 200 response.
    """

    metadata: Optional[OutputTransformEventMetadata] = None

    metrics: Optional[OutputTransformEventMetrics] = None
    """Accuracy, precision, recall, and F1 score when corrected JSON is provided."""

    order_matching: Optional[bool] = FieldInfo(alias="orderMatching", default=None)
    """
    Indicates whether array order matters when comparing corrected JSON with
    extracted JSON.
    """

    pipeline_id: Optional[str] = FieldInfo(alias="pipelineID", default=None)
    """ID of pipeline that transformed the original input data."""

    published_at: Optional[datetime] = FieldInfo(alias="publishedAt", default=None)
    """
    Timestamp indicating when the transform was published via webhook and received a
    successful 200 response. Value is `null` if the transformation hasn't been sent.
    """

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)
    """Presigned S3 URL for the input content uploaded to S3."""

    transformation_id: Optional[str] = FieldInfo(alias="transformationID", default=None)
    """
    Unique ID for each transformation output generated by bem following Segment's
    KSUID conventions.
    """

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of workflow that this event is associated with."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of workflow that this event is associated with."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of workflow that this event is associated with."""


class OutputExtractEventCorrectedContentOutput(BaseModel):
    output: Optional[List[Optional[AnyType]]] = None


OutputExtractEventCorrectedContent: TypeAlias = Union[
    OutputExtractEventCorrectedContentOutput, List[object], str, float, bool, object, None
]


class OutputExtractEventInput(BaseModel):
    input_content: Optional[str] = FieldInfo(alias="inputContent", default=None)

    input_type: Optional[str] = FieldInfo(alias="inputType", default=None)

    json_input_content: Optional[object] = FieldInfo(alias="jsonInputContent", default=None)

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)


class OutputExtractEventMetadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class OutputExtractEvent(BaseModel):
    """V3 event variants that do not exist in the shared `Event` union.

    `ExtractEvent` and `ClassifyEvent` are emitted only by V3-era function types
    (`extract` and `classify`). The shared `Event` union in `specs/events/models.tsp`
    predates these types and continues to describe V2 / V1-alpha responses verbatim;
    V3 response payloads add the new variants via the `EventV3` union below while
    keeping every shared variant intact for backward compatibility.
    """

    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    function_id: str = FieldInfo(alias="functionID")
    """Unique identifier of function that this event is associated with."""

    function_name: str = FieldInfo(alias="functionName")
    """Unique name of function that this event is associated with."""

    item_count: int = FieldInfo(alias="itemCount")
    """The number of items that were transformed.

    Used for batch transformations to indicate how many items were transformed.
    """

    item_offset: int = FieldInfo(alias="itemOffset")
    """The offset of the first item that was transformed.

    Used for batch transformations to indicate which item in the batch this event
    corresponds to.
    """

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    transformed_content: object = FieldInfo(alias="transformedContent")
    """The transformed content of the input.

    The structure of this object is defined by the function configuration.
    """

    avg_confidence: Optional[float] = FieldInfo(alias="avgConfidence", default=None)
    """Average confidence score across all extracted fields, in the range [0, 1]."""

    call_id: Optional[str] = FieldInfo(alias="callID", default=None)
    """Unique identifier of workflow call that this event is associated with."""

    corrected_content: Optional[OutputExtractEventCorrectedContent] = FieldInfo(alias="correctedContent", default=None)
    """Corrected feedback provided for fine-tuning purposes."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    event_type: Optional[Literal["extract"]] = FieldInfo(alias="eventType", default=None)

    field_confidences: Optional[object] = FieldInfo(alias="fieldConfidences", default=None)
    """Per-field confidence scores.

    A JSON object mapping RFC 6901 JSON Pointer paths (e.g. `"/invoiceNumber"`) to
    float values in the range [0, 1] indicating the model's confidence in each
    extracted field value.
    """

    function_call_id: Optional[str] = FieldInfo(alias="functionCallID", default=None)
    """Unique identifier of function call that this event is associated with."""

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    function_version_num: Optional[int] = FieldInfo(alias="functionVersionNum", default=None)
    """Version number of function that this event is associated with."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    inputs: Optional[List[OutputExtractEventInput]] = None
    """Array of transformation inputs with their types and S3 URLs."""

    input_type: Optional[
        Literal[
            "csv",
            "docx",
            "email",
            "heic",
            "html",
            "jpeg",
            "json",
            "heif",
            "m4a",
            "mp3",
            "pdf",
            "png",
            "text",
            "wav",
            "webp",
            "xls",
            "xlsx",
            "xml",
        ]
    ] = FieldInfo(alias="inputType", default=None)
    """The input type of the content you're sending for transformation."""

    invalid_properties: Optional[List[str]] = FieldInfo(alias="invalidProperties", default=None)
    """List of properties that were invalid in the input."""

    metadata: Optional[OutputExtractEventMetadata] = None

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)
    """Presigned S3 URL for the input content uploaded to S3."""

    transformation_id: Optional[str] = FieldInfo(alias="transformationID", default=None)
    """
    Unique ID for each transformation output generated by bem following Segment's
    KSUID conventions.
    """

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of workflow that this event is associated with."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of workflow that this event is associated with."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of workflow that this event is associated with."""


class OutputRouteEventMetadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class OutputRouteEvent(BaseModel):
    choice: str
    """The choice made by the router function."""

    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    function_id: str = FieldInfo(alias="functionID")
    """Unique identifier of function that this event is associated with."""

    function_name: str = FieldInfo(alias="functionName")
    """Unique name of function that this event is associated with."""

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    call_id: Optional[str] = FieldInfo(alias="callID", default=None)
    """Unique identifier of workflow call that this event is associated with."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    event_type: Optional[Literal["route"]] = FieldInfo(alias="eventType", default=None)

    function_call_id: Optional[str] = FieldInfo(alias="functionCallID", default=None)
    """Unique identifier of function call that this event is associated with."""

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    function_version_num: Optional[int] = FieldInfo(alias="functionVersionNum", default=None)
    """Version number of function that this event is associated with."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    metadata: Optional[OutputRouteEventMetadata] = None

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)
    """The presigned S3 URL of the file that was routed."""

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of workflow that this event is associated with."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of workflow that this event is associated with."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of workflow that this event is associated with."""


class OutputClassifyEventMetadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class OutputClassifyEvent(BaseModel):
    choice: str
    """The classification chosen by the classify function."""

    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    function_id: str = FieldInfo(alias="functionID")
    """Unique identifier of function that this event is associated with."""

    function_name: str = FieldInfo(alias="functionName")
    """Unique name of function that this event is associated with."""

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    call_id: Optional[str] = FieldInfo(alias="callID", default=None)
    """Unique identifier of workflow call that this event is associated with."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    event_type: Optional[Literal["classify"]] = FieldInfo(alias="eventType", default=None)

    function_call_id: Optional[str] = FieldInfo(alias="functionCallID", default=None)
    """Unique identifier of function call that this event is associated with."""

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    function_version_num: Optional[int] = FieldInfo(alias="functionVersionNum", default=None)
    """Version number of function that this event is associated with."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    metadata: Optional[OutputClassifyEventMetadata] = None

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)
    """The presigned S3 URL of the file that was classified."""

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of workflow that this event is associated with."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of workflow that this event is associated with."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of workflow that this event is associated with."""


class OutputSplitCollectionEventPrintPageOutputItem(BaseModel):
    item_offset: Optional[int] = FieldInfo(alias="itemOffset", default=None)

    item_reference_id: Optional[str] = FieldInfo(alias="itemReferenceID", default=None)

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)


class OutputSplitCollectionEventPrintPageOutput(BaseModel):
    item_count: Optional[int] = FieldInfo(alias="itemCount", default=None)

    items: Optional[List[OutputSplitCollectionEventPrintPageOutputItem]] = None


class OutputSplitCollectionEventSemanticPageOutputItem(BaseModel):
    item_class: Optional[str] = FieldInfo(alias="itemClass", default=None)

    item_class_count: Optional[int] = FieldInfo(alias="itemClassCount", default=None)

    item_class_offset: Optional[int] = FieldInfo(alias="itemClassOffset", default=None)

    item_offset: Optional[int] = FieldInfo(alias="itemOffset", default=None)

    item_reference_id: Optional[str] = FieldInfo(alias="itemReferenceID", default=None)

    page_end: Optional[int] = FieldInfo(alias="pageEnd", default=None)

    page_start: Optional[int] = FieldInfo(alias="pageStart", default=None)

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)


class OutputSplitCollectionEventSemanticPageOutput(BaseModel):
    item_count: Optional[int] = FieldInfo(alias="itemCount", default=None)

    items: Optional[List[OutputSplitCollectionEventSemanticPageOutputItem]] = None

    page_count: Optional[int] = FieldInfo(alias="pageCount", default=None)


class OutputSplitCollectionEventMetadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class OutputSplitCollectionEvent(BaseModel):
    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    function_id: str = FieldInfo(alias="functionID")
    """Unique identifier of function that this event is associated with."""

    function_name: str = FieldInfo(alias="functionName")
    """Unique name of function that this event is associated with."""

    output_type: Literal["print_page", "semantic_page"] = FieldInfo(alias="outputType")

    print_page_output: OutputSplitCollectionEventPrintPageOutput = FieldInfo(alias="printPageOutput")

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    semantic_page_output: OutputSplitCollectionEventSemanticPageOutput = FieldInfo(alias="semanticPageOutput")

    call_id: Optional[str] = FieldInfo(alias="callID", default=None)
    """Unique identifier of workflow call that this event is associated with."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    event_type: Optional[Literal["split_collection"]] = FieldInfo(alias="eventType", default=None)

    function_call_id: Optional[str] = FieldInfo(alias="functionCallID", default=None)
    """Unique identifier of function call that this event is associated with."""

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    function_version_num: Optional[int] = FieldInfo(alias="functionVersionNum", default=None)
    """Version number of function that this event is associated with."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    metadata: Optional[OutputSplitCollectionEventMetadata] = None

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of workflow that this event is associated with."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of workflow that this event is associated with."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of workflow that this event is associated with."""


class OutputSplitItemEventMetadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class OutputSplitItemEventPrintPageOutput(BaseModel):
    collection_reference_id: Optional[str] = FieldInfo(alias="collectionReferenceID", default=None)

    item_count: Optional[int] = FieldInfo(alias="itemCount", default=None)

    item_offset: Optional[int] = FieldInfo(alias="itemOffset", default=None)

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)


class OutputSplitItemEventSemanticPageOutput(BaseModel):
    collection_reference_id: Optional[str] = FieldInfo(alias="collectionReferenceID", default=None)

    item_class: Optional[str] = FieldInfo(alias="itemClass", default=None)

    item_class_count: Optional[int] = FieldInfo(alias="itemClassCount", default=None)

    item_class_offset: Optional[int] = FieldInfo(alias="itemClassOffset", default=None)

    item_count: Optional[int] = FieldInfo(alias="itemCount", default=None)

    item_offset: Optional[int] = FieldInfo(alias="itemOffset", default=None)

    page_count: Optional[int] = FieldInfo(alias="pageCount", default=None)

    page_end: Optional[int] = FieldInfo(alias="pageEnd", default=None)

    page_start: Optional[int] = FieldInfo(alias="pageStart", default=None)

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)


class OutputSplitItemEvent(BaseModel):
    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    function_id: str = FieldInfo(alias="functionID")
    """Unique identifier of function that this event is associated with."""

    function_name: str = FieldInfo(alias="functionName")
    """Unique name of function that this event is associated with."""

    output_type: Literal["print_page", "semantic_page"] = FieldInfo(alias="outputType")

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    call_id: Optional[str] = FieldInfo(alias="callID", default=None)
    """Unique identifier of workflow call that this event is associated with."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    event_type: Optional[Literal["split_item"]] = FieldInfo(alias="eventType", default=None)

    function_call_id: Optional[str] = FieldInfo(alias="functionCallID", default=None)
    """Unique identifier of function call that this event is associated with."""

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    function_version_num: Optional[int] = FieldInfo(alias="functionVersionNum", default=None)
    """Version number of function that this event is associated with."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    metadata: Optional[OutputSplitItemEventMetadata] = None

    print_page_output: Optional[OutputSplitItemEventPrintPageOutput] = FieldInfo(alias="printPageOutput", default=None)

    semantic_page_output: Optional[OutputSplitItemEventSemanticPageOutput] = FieldInfo(
        alias="semanticPageOutput", default=None
    )

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of workflow that this event is associated with."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of workflow that this event is associated with."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of workflow that this event is associated with."""


class OutputJoinEventItem(BaseModel):
    item_count: int = FieldInfo(alias="itemCount")
    """The number of items that were transformed."""

    item_offset: int = FieldInfo(alias="itemOffset")
    """The offset of the first item that was transformed.

    Used for batch transformations to indicate which item in the batch this event
    corresponds to.
    """

    item_reference_id: str = FieldInfo(alias="itemReferenceID")
    """The unique ID you use internally to refer to this data point."""

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)
    """The presigned S3 URL of the file that was joined."""


class OutputJoinEventMetadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class OutputJoinEvent(BaseModel):
    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    function_id: str = FieldInfo(alias="functionID")
    """Unique identifier of function that this event is associated with."""

    function_name: str = FieldInfo(alias="functionName")
    """Unique name of function that this event is associated with."""

    invalid_properties: List[str] = FieldInfo(alias="invalidProperties")
    """List of properties that were invalid in the input."""

    items: List[OutputJoinEventItem]
    """The items that were joined."""

    join_type: Literal["standard"] = FieldInfo(alias="joinType")
    """The type of join that was performed."""

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    transformed_content: object = FieldInfo(alias="transformedContent")
    """The transformed content of the input.

    The structure of this object is defined by the function configuration.
    """

    avg_confidence: Optional[float] = FieldInfo(alias="avgConfidence", default=None)
    """Average confidence score across all extracted fields, in the range [0, 1]."""

    call_id: Optional[str] = FieldInfo(alias="callID", default=None)
    """Unique identifier of workflow call that this event is associated with."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    event_type: Optional[Literal["join"]] = FieldInfo(alias="eventType", default=None)

    field_confidences: Optional[object] = FieldInfo(alias="fieldConfidences", default=None)
    """Per-field confidence scores.

    A JSON object mapping RFC 6901 JSON Pointer paths (e.g. `"/invoiceNumber"`) to
    float values in the range [0, 1] indicating the model's confidence in each
    extracted field value.
    """

    function_call_id: Optional[str] = FieldInfo(alias="functionCallID", default=None)
    """Unique identifier of function call that this event is associated with."""

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    function_version_num: Optional[int] = FieldInfo(alias="functionVersionNum", default=None)
    """Version number of function that this event is associated with."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    metadata: Optional[OutputJoinEventMetadata] = None

    transformation_id: Optional[str] = FieldInfo(alias="transformationID", default=None)
    """
    Unique ID for each transformation output generated by bem following Segment's
    KSUID conventions.
    """

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of workflow that this event is associated with."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of workflow that this event is associated with."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of workflow that this event is associated with."""


class OutputEnrichEventMetadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class OutputEnrichEvent(BaseModel):
    enriched_content: object = FieldInfo(alias="enrichedContent")
    """The enriched content produced by the enrich function.

    Contains the input data augmented with results from semantic search against
    collections.
    """

    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    function_id: str = FieldInfo(alias="functionID")
    """Unique identifier of function that this event is associated with."""

    function_name: str = FieldInfo(alias="functionName")
    """Unique name of function that this event is associated with."""

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    call_id: Optional[str] = FieldInfo(alias="callID", default=None)
    """Unique identifier of workflow call that this event is associated with."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    event_type: Optional[Literal["enrich"]] = FieldInfo(alias="eventType", default=None)

    function_call_id: Optional[str] = FieldInfo(alias="functionCallID", default=None)
    """Unique identifier of function call that this event is associated with."""

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    function_version_num: Optional[int] = FieldInfo(alias="functionVersionNum", default=None)
    """Version number of function that this event is associated with."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    metadata: Optional[OutputEnrichEventMetadata] = None

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of workflow that this event is associated with."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of workflow that this event is associated with."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of workflow that this event is associated with."""


class OutputCollectionProcessingEventMetadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class OutputCollectionProcessingEvent(BaseModel):
    collection_id: str = FieldInfo(alias="collectionID")
    """Unique identifier of the collection."""

    collection_name: str = FieldInfo(alias="collectionName")
    """Name/path of the collection."""

    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    operation: Literal["add", "update"]
    """The operation performed (add or update)."""

    processed_count: int = FieldInfo(alias="processedCount")
    """Number of items successfully processed."""

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    status: Literal["success", "failed"]
    """Processing status (success or failed)."""

    collection_item_ids: Optional[List[str]] = FieldInfo(alias="collectionItemIDs", default=None)
    """Array of collection item KSUIDs that were added or updated."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    error_message: Optional[str] = FieldInfo(alias="errorMessage", default=None)
    """Error message if processing failed."""

    event_type: Optional[Literal["collection_processing"]] = FieldInfo(alias="eventType", default=None)

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    metadata: Optional[OutputCollectionProcessingEventMetadata] = None


class OutputSendEventGoogleDriveOutput(BaseModel):
    """Metadata returned when a Send function delivers to Google Drive."""

    file_name: str = FieldInfo(alias="fileName")
    """Name of the file created in Google Drive."""

    folder_id: str = FieldInfo(alias="folderID")
    """ID of the Google Drive folder the file was placed in."""


class OutputSendEventMetadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class OutputSendEventS3Output(BaseModel):
    """Metadata returned when a Send function delivers to an S3 bucket."""

    bucket_name: str = FieldInfo(alias="bucketName")
    """Name of the S3 bucket the payload was written to."""

    key: str
    """Object key under which the payload was stored."""


class OutputSendEventWebhookOutput(BaseModel):
    """Metadata returned when a Send function delivers to a webhook."""

    http_response_body: str = FieldInfo(alias="httpResponseBody")
    """Raw HTTP response body returned by the webhook endpoint."""

    http_status_code: int = FieldInfo(alias="httpStatusCode")
    """HTTP status code returned by the webhook endpoint."""


class OutputSendEvent(BaseModel):
    delivery_status: Literal["success", "skip"] = FieldInfo(alias="deliveryStatus")
    """Outcome of a Send function's delivery attempt."""

    destination_type: Literal["webhook", "s3", "google_drive"] = FieldInfo(alias="destinationType")
    """Destination type for a Send function."""

    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    function_id: str = FieldInfo(alias="functionID")
    """Unique identifier of function that this event is associated with."""

    function_name: str = FieldInfo(alias="functionName")
    """Unique name of function that this event is associated with."""

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    call_id: Optional[str] = FieldInfo(alias="callID", default=None)
    """Unique identifier of workflow call that this event is associated with."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    delivered_content: Optional[object] = FieldInfo(alias="deliveredContent", default=None)
    """
    The full protocol event JSON that was delivered — identical to what subscription
    publish would deliver for the same event. For ad-hoc calls with a JSON file
    input, contains the raw input JSON. For ad-hoc calls with a binary file input,
    contains {"s3URL": "<presigned-url>"}.
    """

    event_type: Optional[Literal["send"]] = FieldInfo(alias="eventType", default=None)

    function_call_id: Optional[str] = FieldInfo(alias="functionCallID", default=None)
    """Unique identifier of function call that this event is associated with."""

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    function_version_num: Optional[int] = FieldInfo(alias="functionVersionNum", default=None)
    """Version number of function that this event is associated with."""

    google_drive_output: Optional[OutputSendEventGoogleDriveOutput] = FieldInfo(alias="googleDriveOutput", default=None)
    """Metadata returned when a Send function delivers to Google Drive."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    metadata: Optional[OutputSendEventMetadata] = None

    s3_output: Optional[OutputSendEventS3Output] = FieldInfo(alias="s3Output", default=None)
    """Metadata returned when a Send function delivers to an S3 bucket."""

    webhook_output: Optional[OutputSendEventWebhookOutput] = FieldInfo(alias="webhookOutput", default=None)
    """Metadata returned when a Send function delivers to a webhook."""

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of workflow that this event is associated with."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of workflow that this event is associated with."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of workflow that this event is associated with."""


Output: TypeAlias = Annotated[
    Union[
        OutputTransformEvent,
        OutputExtractEvent,
        OutputRouteEvent,
        OutputClassifyEvent,
        OutputSplitCollectionEvent,
        OutputSplitItemEvent,
        ErrorEvent,
        OutputJoinEvent,
        OutputEnrichEvent,
        OutputCollectionProcessingEvent,
        OutputSendEvent,
    ],
    PropertyInfo(discriminator="event_type"),
]


class InputBatchFilesInput(BaseModel):
    input_type: Optional[str] = FieldInfo(alias="inputType", default=None)
    """Input type of the file"""

    item_reference_id: Optional[str] = FieldInfo(alias="itemReferenceID", default=None)
    """Item reference ID"""

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)
    """Presigned S3 URL for the file"""


class InputBatchFiles(BaseModel):
    inputs: Optional[List[InputBatchFilesInput]] = None


class InputSingleFile(BaseModel):
    input_type: Optional[str] = FieldInfo(alias="inputType", default=None)
    """Input type of the file"""

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)
    """Presigned S3 URL for the file"""


class Input(BaseModel):
    """Input to the main function call."""

    batch_files: Optional[InputBatchFiles] = FieldInfo(alias="batchFiles", default=None)

    single_file: Optional[InputSingleFile] = FieldInfo(alias="singleFile", default=None)


class Call(BaseModel):
    """A workflow call returned by the V3 API.

    Compared to the V2 `Call` model:
    - Terminal outputs are split into `outputs` (non-error events) and `errors` (error events)
    - `callType` and function-scoped fields are removed — V3 calls are always workflow calls
    - The deprecated `functionCalls` field is removed (use `GET /v3/calls/{callID}/trace`)
    - `url` and `traceUrl` hint fields are included for resource discovery
    """

    call_id: str = FieldInfo(alias="callID")
    """Unique identifier of the call."""

    created_at: datetime = FieldInfo(alias="createdAt")
    """The date and time the call was created."""

    errors: List[ErrorEvent]
    """Terminal error events of this call.

    Workflow calls are not atomic — `errors` and `outputs` may both be non-empty if
    some enclosed function calls succeeded and others failed.

    Retrieve individual errors via `GET /v3/errors/{eventID}`.
    """

    outputs: List[Output]
    """
    Terminal non-error outputs of this call: primary events (non-split-collection)
    that did not trigger any downstream function calls. Workflow calls are not
    atomic — `outputs` and `errors` may both be non-empty if some enclosed function
    calls succeeded and others failed.

    Each element is a polymorphic event object; inspect `eventType` to determine the
    type. Retrieve individual outputs via `GET /v3/outputs/{eventID}`.
    """

    trace_url: str = FieldInfo(alias="traceUrl")
    """Hint URL for the full execution trace: `GET /v3/calls/{callID}/trace`."""

    url: str
    """Hint URL for retrieving this call: `GET /v3/calls/{callID}`."""

    call_reference_id: Optional[str] = FieldInfo(alias="callReferenceID", default=None)
    """Your reference ID for this call, propagated from the original request."""

    finished_at: Optional[datetime] = FieldInfo(alias="finishedAt", default=None)
    """The date and time the call finished.

    Only set once status is `completed` or `failed`.
    """

    input: Optional[Input] = None
    """Input to the main function call."""

    status: Optional[Literal["pending", "running", "completed", "failed"]] = None
    """Status of call."""

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of the workflow."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of the workflow."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of the workflow."""
