# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional
from datetime import datetime
from typing_extensions import Literal

from pydantic import Field as FieldInfo

from .._models import BaseModel
from .inbound_email_event import InboundEmailEvent

__all__ = ["CollectionProcessingWebhookEvent", "Metadata"]


class Metadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class CollectionProcessingWebhookEvent(BaseModel):
    collection_id: str = FieldInfo(alias="collectionID")
    """Unique identifier of the collection."""

    collection_name: str = FieldInfo(alias="collectionName")
    """Name/path of the collection."""

    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    operation: Literal["add", "update"]
    """The operation performed (add or update)."""

    processed_count: int = FieldInfo(alias="processedCount")
    """Number of items successfully processed."""

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    status: Literal["success", "failed"]
    """Processing status (success or failed)."""

    collection_item_ids: Optional[List[str]] = FieldInfo(alias="collectionItemIDs", default=None)
    """Array of collection item KSUIDs that were added or updated."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    error_message: Optional[str] = FieldInfo(alias="errorMessage", default=None)
    """Error message if processing failed."""

    event_type: Optional[Literal["collection_processing"]] = FieldInfo(alias="eventType", default=None)

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    metadata: Optional[Metadata] = None
