# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Union, Optional
from datetime import datetime
from typing_extensions import Literal, Annotated, TypeAlias

from pydantic import Field as FieldInfo

from .._utils import PropertyInfo
from .._models import BaseModel
from .any_type import AnyType
from .error_event import ErrorEvent
from .inbound_email_event import InboundEmailEvent

__all__ = [
    "Event",
    "TransformEvent",
    "TransformEventCorrectedContent",
    "TransformEventCorrectedContentOutput",
    "TransformEventInput",
    "TransformEventMetadata",
    "TransformEventMetrics",
    "TransformEventMetricsDifference",
    "TransformEventMetricsMetrics",
    "RouteEvent",
    "RouteEventMetadata",
    "SplitCollectionEvent",
    "SplitCollectionEventPrintPageOutput",
    "SplitCollectionEventPrintPageOutputItem",
    "SplitCollectionEventSemanticPageOutput",
    "SplitCollectionEventSemanticPageOutputItem",
    "SplitCollectionEventMetadata",
    "SplitItemEvent",
    "SplitItemEventMetadata",
    "SplitItemEventPrintPageOutput",
    "SplitItemEventSemanticPageOutput",
    "JoinEvent",
    "JoinEventItem",
    "JoinEventMetadata",
    "EnrichEvent",
    "EnrichEventMetadata",
    "CollectionProcessingEvent",
    "CollectionProcessingEventMetadata",
    "SendEvent",
    "SendEventGoogleDriveOutput",
    "SendEventMetadata",
    "SendEventS3Output",
    "SendEventWebhookOutput",
]


class TransformEventCorrectedContentOutput(BaseModel):
    output: Optional[List[Optional[AnyType]]] = None


TransformEventCorrectedContent: TypeAlias = Union[
    TransformEventCorrectedContentOutput, List[object], str, float, bool, object, None
]


class TransformEventInput(BaseModel):
    input_content: Optional[str] = FieldInfo(alias="inputContent", default=None)

    input_type: Optional[str] = FieldInfo(alias="inputType", default=None)

    json_input_content: Optional[object] = FieldInfo(alias="jsonInputContent", default=None)

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)


class TransformEventMetadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class TransformEventMetricsDifference(BaseModel):
    category: Optional[str] = None

    corrected_val: Optional[object] = FieldInfo(alias="correctedVal", default=None)

    extracted_val: Optional[object] = FieldInfo(alias="extractedVal", default=None)

    json_pointer: Optional[str] = FieldInfo(alias="jsonPointer", default=None)


class TransformEventMetricsMetrics(BaseModel):
    accuracy: Optional[float] = None

    f1_score: Optional[float] = FieldInfo(alias="f1Score", default=None)

    precision: Optional[float] = None

    recall: Optional[float] = None


class TransformEventMetrics(BaseModel):
    """Accuracy, precision, recall, and F1 score when corrected JSON is provided."""

    differences: Optional[List[TransformEventMetricsDifference]] = None

    metrics: Optional[TransformEventMetricsMetrics] = None


class TransformEvent(BaseModel):
    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    function_id: str = FieldInfo(alias="functionID")
    """Unique identifier of function that this event is associated with."""

    function_name: str = FieldInfo(alias="functionName")
    """Unique name of function that this event is associated with."""

    item_count: int = FieldInfo(alias="itemCount")
    """The number of items that were transformed.

    Used for batch transformations to indicate how many items were transformed.
    """

    item_offset: int = FieldInfo(alias="itemOffset")
    """The offset of the first item that was transformed.

    Used for batch transformations to indicate which item in the batch this event
    corresponds to.
    """

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    transformed_content: object = FieldInfo(alias="transformedContent")
    """The transformed content of the input.

    The structure of this object is defined by the function configuration.
    """

    avg_confidence: Optional[float] = FieldInfo(alias="avgConfidence", default=None)
    """Average confidence score across all extracted fields, in the range [0, 1]."""

    call_id: Optional[str] = FieldInfo(alias="callID", default=None)
    """Unique identifier of workflow call that this event is associated with."""

    corrected_content: Optional[TransformEventCorrectedContent] = FieldInfo(alias="correctedContent", default=None)
    """Corrected feedback provided for fine-tuning purposes."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    event_type: Optional[Literal["transform"]] = FieldInfo(alias="eventType", default=None)

    field_confidences: Optional[object] = FieldInfo(alias="fieldConfidences", default=None)
    """Per-field confidence scores.

    A JSON object mapping RFC 6901 JSON Pointer paths (e.g. `"/invoiceNumber"`) to
    float values in the range [0, 1] indicating the model's confidence in each
    extracted field value.
    """

    function_call_id: Optional[str] = FieldInfo(alias="functionCallID", default=None)
    """Unique identifier of function call that this event is associated with."""

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    function_version_num: Optional[int] = FieldInfo(alias="functionVersionNum", default=None)
    """Version number of function that this event is associated with."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    inputs: Optional[List[TransformEventInput]] = None
    """Array of transformation inputs with their types and S3 URLs."""

    input_type: Optional[
        Literal[
            "csv",
            "docx",
            "email",
            "heic",
            "html",
            "jpeg",
            "json",
            "heif",
            "m4a",
            "mp3",
            "pdf",
            "png",
            "text",
            "wav",
            "webp",
            "xls",
            "xlsx",
            "xml",
        ]
    ] = FieldInfo(alias="inputType", default=None)
    """The input type of the content you're sending for transformation."""

    invalid_properties: Optional[List[str]] = FieldInfo(alias="invalidProperties", default=None)
    """List of properties that were invalid in the input."""

    is_regression: Optional[bool] = FieldInfo(alias="isRegression", default=None)
    """Indicates whether this transformation was created as part of a regression test."""

    last_publish_error_at: Optional[str] = FieldInfo(alias="lastPublishErrorAt", default=None)
    """
    Last timestamp indicating when the transform was published via webhook and
    received a non-200 response. Set to `null` on a subsequent retry if the webhook
    service receives a 200 response.
    """

    metadata: Optional[TransformEventMetadata] = None

    metrics: Optional[TransformEventMetrics] = None
    """Accuracy, precision, recall, and F1 score when corrected JSON is provided."""

    order_matching: Optional[bool] = FieldInfo(alias="orderMatching", default=None)
    """
    Indicates whether array order matters when comparing corrected JSON with
    extracted JSON.
    """

    pipeline_id: Optional[str] = FieldInfo(alias="pipelineID", default=None)
    """ID of pipeline that transformed the original input data."""

    published_at: Optional[datetime] = FieldInfo(alias="publishedAt", default=None)
    """
    Timestamp indicating when the transform was published via webhook and received a
    successful 200 response. Value is `null` if the transformation hasn't been sent.
    """

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)
    """Presigned S3 URL for the input content uploaded to S3."""

    transformation_id: Optional[str] = FieldInfo(alias="transformationID", default=None)
    """
    Unique ID for each transformation output generated by bem following Segment's
    KSUID conventions.
    """

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of workflow that this event is associated with."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of workflow that this event is associated with."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of workflow that this event is associated with."""


class RouteEventMetadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class RouteEvent(BaseModel):
    choice: str
    """The choice made by the router function."""

    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    function_id: str = FieldInfo(alias="functionID")
    """Unique identifier of function that this event is associated with."""

    function_name: str = FieldInfo(alias="functionName")
    """Unique name of function that this event is associated with."""

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    call_id: Optional[str] = FieldInfo(alias="callID", default=None)
    """Unique identifier of workflow call that this event is associated with."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    event_type: Optional[Literal["route"]] = FieldInfo(alias="eventType", default=None)

    function_call_id: Optional[str] = FieldInfo(alias="functionCallID", default=None)
    """Unique identifier of function call that this event is associated with."""

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    function_version_num: Optional[int] = FieldInfo(alias="functionVersionNum", default=None)
    """Version number of function that this event is associated with."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    metadata: Optional[RouteEventMetadata] = None

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)
    """The presigned S3 URL of the file that was routed."""

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of workflow that this event is associated with."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of workflow that this event is associated with."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of workflow that this event is associated with."""


class SplitCollectionEventPrintPageOutputItem(BaseModel):
    item_offset: Optional[int] = FieldInfo(alias="itemOffset", default=None)

    item_reference_id: Optional[str] = FieldInfo(alias="itemReferenceID", default=None)

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)


class SplitCollectionEventPrintPageOutput(BaseModel):
    item_count: Optional[int] = FieldInfo(alias="itemCount", default=None)

    items: Optional[List[SplitCollectionEventPrintPageOutputItem]] = None


class SplitCollectionEventSemanticPageOutputItem(BaseModel):
    item_class: Optional[str] = FieldInfo(alias="itemClass", default=None)

    item_class_count: Optional[int] = FieldInfo(alias="itemClassCount", default=None)

    item_class_offset: Optional[int] = FieldInfo(alias="itemClassOffset", default=None)

    item_offset: Optional[int] = FieldInfo(alias="itemOffset", default=None)

    item_reference_id: Optional[str] = FieldInfo(alias="itemReferenceID", default=None)

    page_end: Optional[int] = FieldInfo(alias="pageEnd", default=None)

    page_start: Optional[int] = FieldInfo(alias="pageStart", default=None)

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)


class SplitCollectionEventSemanticPageOutput(BaseModel):
    item_count: Optional[int] = FieldInfo(alias="itemCount", default=None)

    items: Optional[List[SplitCollectionEventSemanticPageOutputItem]] = None

    page_count: Optional[int] = FieldInfo(alias="pageCount", default=None)


class SplitCollectionEventMetadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class SplitCollectionEvent(BaseModel):
    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    function_id: str = FieldInfo(alias="functionID")
    """Unique identifier of function that this event is associated with."""

    function_name: str = FieldInfo(alias="functionName")
    """Unique name of function that this event is associated with."""

    output_type: Literal["print_page", "semantic_page"] = FieldInfo(alias="outputType")

    print_page_output: SplitCollectionEventPrintPageOutput = FieldInfo(alias="printPageOutput")

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    semantic_page_output: SplitCollectionEventSemanticPageOutput = FieldInfo(alias="semanticPageOutput")

    call_id: Optional[str] = FieldInfo(alias="callID", default=None)
    """Unique identifier of workflow call that this event is associated with."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    event_type: Optional[Literal["split_collection"]] = FieldInfo(alias="eventType", default=None)

    function_call_id: Optional[str] = FieldInfo(alias="functionCallID", default=None)
    """Unique identifier of function call that this event is associated with."""

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    function_version_num: Optional[int] = FieldInfo(alias="functionVersionNum", default=None)
    """Version number of function that this event is associated with."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    metadata: Optional[SplitCollectionEventMetadata] = None

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of workflow that this event is associated with."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of workflow that this event is associated with."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of workflow that this event is associated with."""


class SplitItemEventMetadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class SplitItemEventPrintPageOutput(BaseModel):
    collection_reference_id: Optional[str] = FieldInfo(alias="collectionReferenceID", default=None)

    item_count: Optional[int] = FieldInfo(alias="itemCount", default=None)

    item_offset: Optional[int] = FieldInfo(alias="itemOffset", default=None)

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)


class SplitItemEventSemanticPageOutput(BaseModel):
    collection_reference_id: Optional[str] = FieldInfo(alias="collectionReferenceID", default=None)

    item_class: Optional[str] = FieldInfo(alias="itemClass", default=None)

    item_class_count: Optional[int] = FieldInfo(alias="itemClassCount", default=None)

    item_class_offset: Optional[int] = FieldInfo(alias="itemClassOffset", default=None)

    item_count: Optional[int] = FieldInfo(alias="itemCount", default=None)

    item_offset: Optional[int] = FieldInfo(alias="itemOffset", default=None)

    page_count: Optional[int] = FieldInfo(alias="pageCount", default=None)

    page_end: Optional[int] = FieldInfo(alias="pageEnd", default=None)

    page_start: Optional[int] = FieldInfo(alias="pageStart", default=None)

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)


class SplitItemEvent(BaseModel):
    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    function_id: str = FieldInfo(alias="functionID")
    """Unique identifier of function that this event is associated with."""

    function_name: str = FieldInfo(alias="functionName")
    """Unique name of function that this event is associated with."""

    output_type: Literal["print_page", "semantic_page"] = FieldInfo(alias="outputType")

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    call_id: Optional[str] = FieldInfo(alias="callID", default=None)
    """Unique identifier of workflow call that this event is associated with."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    event_type: Optional[Literal["split_item"]] = FieldInfo(alias="eventType", default=None)

    function_call_id: Optional[str] = FieldInfo(alias="functionCallID", default=None)
    """Unique identifier of function call that this event is associated with."""

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    function_version_num: Optional[int] = FieldInfo(alias="functionVersionNum", default=None)
    """Version number of function that this event is associated with."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    metadata: Optional[SplitItemEventMetadata] = None

    print_page_output: Optional[SplitItemEventPrintPageOutput] = FieldInfo(alias="printPageOutput", default=None)

    semantic_page_output: Optional[SplitItemEventSemanticPageOutput] = FieldInfo(
        alias="semanticPageOutput", default=None
    )

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of workflow that this event is associated with."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of workflow that this event is associated with."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of workflow that this event is associated with."""


class JoinEventItem(BaseModel):
    item_count: int = FieldInfo(alias="itemCount")
    """The number of items that were transformed."""

    item_offset: int = FieldInfo(alias="itemOffset")
    """The offset of the first item that was transformed.

    Used for batch transformations to indicate which item in the batch this event
    corresponds to.
    """

    item_reference_id: str = FieldInfo(alias="itemReferenceID")
    """The unique ID you use internally to refer to this data point."""

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)
    """The presigned S3 URL of the file that was joined."""


class JoinEventMetadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class JoinEvent(BaseModel):
    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    function_id: str = FieldInfo(alias="functionID")
    """Unique identifier of function that this event is associated with."""

    function_name: str = FieldInfo(alias="functionName")
    """Unique name of function that this event is associated with."""

    invalid_properties: List[str] = FieldInfo(alias="invalidProperties")
    """List of properties that were invalid in the input."""

    items: List[JoinEventItem]
    """The items that were joined."""

    join_type: Literal["standard"] = FieldInfo(alias="joinType")
    """The type of join that was performed."""

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    transformed_content: object = FieldInfo(alias="transformedContent")
    """The transformed content of the input.

    The structure of this object is defined by the function configuration.
    """

    avg_confidence: Optional[float] = FieldInfo(alias="avgConfidence", default=None)
    """Average confidence score across all extracted fields, in the range [0, 1]."""

    call_id: Optional[str] = FieldInfo(alias="callID", default=None)
    """Unique identifier of workflow call that this event is associated with."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    event_type: Optional[Literal["join"]] = FieldInfo(alias="eventType", default=None)

    field_confidences: Optional[object] = FieldInfo(alias="fieldConfidences", default=None)
    """Per-field confidence scores.

    A JSON object mapping RFC 6901 JSON Pointer paths (e.g. `"/invoiceNumber"`) to
    float values in the range [0, 1] indicating the model's confidence in each
    extracted field value.
    """

    function_call_id: Optional[str] = FieldInfo(alias="functionCallID", default=None)
    """Unique identifier of function call that this event is associated with."""

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    function_version_num: Optional[int] = FieldInfo(alias="functionVersionNum", default=None)
    """Version number of function that this event is associated with."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    metadata: Optional[JoinEventMetadata] = None

    transformation_id: Optional[str] = FieldInfo(alias="transformationID", default=None)
    """
    Unique ID for each transformation output generated by bem following Segment's
    KSUID conventions.
    """

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of workflow that this event is associated with."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of workflow that this event is associated with."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of workflow that this event is associated with."""


class EnrichEventMetadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class EnrichEvent(BaseModel):
    enriched_content: object = FieldInfo(alias="enrichedContent")
    """The enriched content produced by the enrich function.

    Contains the input data augmented with results from semantic search against
    collections.
    """

    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    function_id: str = FieldInfo(alias="functionID")
    """Unique identifier of function that this event is associated with."""

    function_name: str = FieldInfo(alias="functionName")
    """Unique name of function that this event is associated with."""

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    call_id: Optional[str] = FieldInfo(alias="callID", default=None)
    """Unique identifier of workflow call that this event is associated with."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    event_type: Optional[Literal["enrich"]] = FieldInfo(alias="eventType", default=None)

    function_call_id: Optional[str] = FieldInfo(alias="functionCallID", default=None)
    """Unique identifier of function call that this event is associated with."""

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    function_version_num: Optional[int] = FieldInfo(alias="functionVersionNum", default=None)
    """Version number of function that this event is associated with."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    metadata: Optional[EnrichEventMetadata] = None

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of workflow that this event is associated with."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of workflow that this event is associated with."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of workflow that this event is associated with."""


class CollectionProcessingEventMetadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class CollectionProcessingEvent(BaseModel):
    collection_id: str = FieldInfo(alias="collectionID")
    """Unique identifier of the collection."""

    collection_name: str = FieldInfo(alias="collectionName")
    """Name/path of the collection."""

    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    operation: Literal["add", "update"]
    """The operation performed (add or update)."""

    processed_count: int = FieldInfo(alias="processedCount")
    """Number of items successfully processed."""

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    status: Literal["success", "failed"]
    """Processing status (success or failed)."""

    collection_item_ids: Optional[List[str]] = FieldInfo(alias="collectionItemIDs", default=None)
    """Array of collection item KSUIDs that were added or updated."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    error_message: Optional[str] = FieldInfo(alias="errorMessage", default=None)
    """Error message if processing failed."""

    event_type: Optional[Literal["collection_processing"]] = FieldInfo(alias="eventType", default=None)

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    metadata: Optional[CollectionProcessingEventMetadata] = None


class SendEventGoogleDriveOutput(BaseModel):
    """Metadata returned when a Send function delivers to Google Drive."""

    file_name: str = FieldInfo(alias="fileName")
    """Name of the file created in Google Drive."""

    folder_id: str = FieldInfo(alias="folderID")
    """ID of the Google Drive folder the file was placed in."""


class SendEventMetadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class SendEventS3Output(BaseModel):
    """Metadata returned when a Send function delivers to an S3 bucket."""

    bucket_name: str = FieldInfo(alias="bucketName")
    """Name of the S3 bucket the payload was written to."""

    key: str
    """Object key under which the payload was stored."""


class SendEventWebhookOutput(BaseModel):
    """Metadata returned when a Send function delivers to a webhook."""

    http_response_body: str = FieldInfo(alias="httpResponseBody")
    """Raw HTTP response body returned by the webhook endpoint."""

    http_status_code: int = FieldInfo(alias="httpStatusCode")
    """HTTP status code returned by the webhook endpoint."""


class SendEvent(BaseModel):
    delivery_status: Literal["success", "skip"] = FieldInfo(alias="deliveryStatus")
    """Outcome of a Send function's delivery attempt."""

    destination_type: Literal["webhook", "s3", "google_drive"] = FieldInfo(alias="destinationType")
    """Destination type for a Send function."""

    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    function_id: str = FieldInfo(alias="functionID")
    """Unique identifier of function that this event is associated with."""

    function_name: str = FieldInfo(alias="functionName")
    """Unique name of function that this event is associated with."""

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    call_id: Optional[str] = FieldInfo(alias="callID", default=None)
    """Unique identifier of workflow call that this event is associated with."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    delivered_content: Optional[object] = FieldInfo(alias="deliveredContent", default=None)
    """
    The full protocol event JSON that was delivered — identical to what subscription
    publish would deliver for the same event. For ad-hoc calls with a JSON file
    input, contains the raw input JSON. For ad-hoc calls with a binary file input,
    contains {"s3URL": "<presigned-url>"}.
    """

    event_type: Optional[Literal["send"]] = FieldInfo(alias="eventType", default=None)

    function_call_id: Optional[str] = FieldInfo(alias="functionCallID", default=None)
    """Unique identifier of function call that this event is associated with."""

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    function_version_num: Optional[int] = FieldInfo(alias="functionVersionNum", default=None)
    """Version number of function that this event is associated with."""

    google_drive_output: Optional[SendEventGoogleDriveOutput] = FieldInfo(alias="googleDriveOutput", default=None)
    """Metadata returned when a Send function delivers to Google Drive."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    metadata: Optional[SendEventMetadata] = None

    s3_output: Optional[SendEventS3Output] = FieldInfo(alias="s3Output", default=None)
    """Metadata returned when a Send function delivers to an S3 bucket."""

    webhook_output: Optional[SendEventWebhookOutput] = FieldInfo(alias="webhookOutput", default=None)
    """Metadata returned when a Send function delivers to a webhook."""

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of workflow that this event is associated with."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of workflow that this event is associated with."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of workflow that this event is associated with."""


Event: TypeAlias = Annotated[
    Union[
        TransformEvent,
        RouteEvent,
        SplitCollectionEvent,
        SplitItemEvent,
        ErrorEvent,
        JoinEvent,
        EnrichEvent,
        CollectionProcessingEvent,
        SendEvent,
    ],
    PropertyInfo(discriminator="event_type"),
]
