# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Union, Optional
from datetime import datetime
from typing_extensions import Literal, TypeAlias

from pydantic import Field as FieldInfo

from .._models import BaseModel
from .any_type import AnyType
from .input_type import InputType
from .inbound_email_event import InboundEmailEvent

__all__ = ["ExtractWebhookEvent", "CorrectedContent", "CorrectedContentOutput", "Input", "Metadata"]


class CorrectedContentOutput(BaseModel):
    output: Optional[List[Optional[AnyType]]] = None


CorrectedContent: TypeAlias = Union[CorrectedContentOutput, List[object], str, float, bool, object, None]


class Input(BaseModel):
    input_content: Optional[str] = FieldInfo(alias="inputContent", default=None)

    input_type: Optional[str] = FieldInfo(alias="inputType", default=None)

    json_input_content: Optional[object] = FieldInfo(alias="jsonInputContent", default=None)

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)


class Metadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class ExtractWebhookEvent(BaseModel):
    """V3 event variants that do not exist in the shared `Event` union.

    `ExtractEvent` and `ClassifyEvent` are emitted only by V3-era function types
    (`extract` and `classify`). The shared `Event` union in `specs/events/models.tsp`
    predates these types and continues to describe V2 / V1-alpha responses verbatim;
    V3 response payloads add the new variants via the `EventV3` union below while
    keeping every shared variant intact for backward compatibility.
    """

    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    function_id: str = FieldInfo(alias="functionID")
    """Unique identifier of function that this event is associated with."""

    function_name: str = FieldInfo(alias="functionName")
    """Unique name of function that this event is associated with."""

    item_count: int = FieldInfo(alias="itemCount")
    """The number of items that were transformed.

    Used for batch transformations to indicate how many items were transformed.
    """

    item_offset: int = FieldInfo(alias="itemOffset")
    """The offset of the first item that was transformed.

    Used for batch transformations to indicate which item in the batch this event
    corresponds to.
    """

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    transformed_content: object = FieldInfo(alias="transformedContent")
    """The transformed content of the input.

    The structure of this object is defined by the function configuration.
    """

    avg_confidence: Optional[float] = FieldInfo(alias="avgConfidence", default=None)
    """Average confidence score across all extracted fields, in the range [0, 1]."""

    call_id: Optional[str] = FieldInfo(alias="callID", default=None)
    """Unique identifier of workflow call that this event is associated with."""

    corrected_content: Optional[CorrectedContent] = FieldInfo(alias="correctedContent", default=None)
    """Corrected feedback provided for fine-tuning purposes."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    event_type: Optional[Literal["extract"]] = FieldInfo(alias="eventType", default=None)

    field_bounding_boxes: Optional[object] = FieldInfo(alias="fieldBoundingBoxes", default=None)
    """Per-field bounding boxes.

    A JSON object mapping RFC 6901 JSON Pointer paths (e.g. `"/invoiceNumber"`,
    `"/items/0/price"`) to the document regions from which each extracted value was
    sourced.
    """

    field_confidences: Optional[object] = FieldInfo(alias="fieldConfidences", default=None)
    """Per-field confidence scores.

    A JSON object mapping RFC 6901 JSON Pointer paths (e.g. `"/invoiceNumber"`) to
    float values in the range [0, 1] indicating the model's confidence in each
    extracted field value.
    """

    function_call_id: Optional[str] = FieldInfo(alias="functionCallID", default=None)
    """Unique identifier of function call that this event is associated with."""

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    function_version_num: Optional[int] = FieldInfo(alias="functionVersionNum", default=None)
    """Version number of function that this event is associated with."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    inputs: Optional[List[Input]] = None
    """Array of transformation inputs with their types and S3 URLs."""

    input_type: Optional[InputType] = FieldInfo(alias="inputType", default=None)
    """The input type of the content you're sending for transformation."""

    invalid_properties: Optional[List[str]] = FieldInfo(alias="invalidProperties", default=None)
    """List of properties that were invalid in the input."""

    metadata: Optional[Metadata] = None

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)
    """Presigned S3 URL for the input content uploaded to S3."""

    transformation_id: Optional[str] = FieldInfo(alias="transformationID", default=None)
    """
    Unique ID for each transformation output generated by bem following Segment's
    KSUID conventions.
    """

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of workflow that this event is associated with."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of workflow that this event is associated with."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of workflow that this event is associated with."""
