# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional
from datetime import datetime
from typing_extensions import Literal

from pydantic import Field as FieldInfo

from .._models import BaseModel
from .inbound_email_event import InboundEmailEvent

__all__ = ["JoinWebhookEvent", "Item", "Metadata"]


class Item(BaseModel):
    item_count: int = FieldInfo(alias="itemCount")
    """The number of items that were transformed."""

    item_offset: int = FieldInfo(alias="itemOffset")
    """The offset of the first item that was transformed.

    Used for batch transformations to indicate which item in the batch this event
    corresponds to.
    """

    item_reference_id: str = FieldInfo(alias="itemReferenceID")
    """The unique ID you use internally to refer to this data point."""

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)
    """The presigned S3 URL of the file that was joined."""


class Metadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class JoinWebhookEvent(BaseModel):
    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    function_id: str = FieldInfo(alias="functionID")
    """Unique identifier of function that this event is associated with."""

    function_name: str = FieldInfo(alias="functionName")
    """Unique name of function that this event is associated with."""

    invalid_properties: List[str] = FieldInfo(alias="invalidProperties")
    """List of properties that were invalid in the input."""

    items: List[Item]
    """The items that were joined."""

    join_type: Literal["standard"] = FieldInfo(alias="joinType")
    """The type of join that was performed."""

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    transformed_content: object = FieldInfo(alias="transformedContent")
    """The transformed content of the input.

    The structure of this object is defined by the function configuration.
    """

    avg_confidence: Optional[float] = FieldInfo(alias="avgConfidence", default=None)
    """Average confidence score across all extracted fields, in the range [0, 1]."""

    call_id: Optional[str] = FieldInfo(alias="callID", default=None)
    """Unique identifier of workflow call that this event is associated with."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    event_type: Optional[Literal["join"]] = FieldInfo(alias="eventType", default=None)

    field_confidences: Optional[object] = FieldInfo(alias="fieldConfidences", default=None)
    """Per-field confidence scores.

    A JSON object mapping RFC 6901 JSON Pointer paths (e.g. `"/invoiceNumber"`) to
    float values in the range [0, 1] indicating the model's confidence in each
    extracted field value.
    """

    function_call_id: Optional[str] = FieldInfo(alias="functionCallID", default=None)
    """Unique identifier of function call that this event is associated with."""

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    function_version_num: Optional[int] = FieldInfo(alias="functionVersionNum", default=None)
    """Version number of function that this event is associated with."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    metadata: Optional[Metadata] = None

    transformation_id: Optional[str] = FieldInfo(alias="transformationID", default=None)
    """
    Unique ID for each transformation output generated by bem following Segment's
    KSUID conventions.
    """

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of workflow that this event is associated with."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of workflow that this event is associated with."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of workflow that this event is associated with."""
