# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Optional
from datetime import datetime
from typing_extensions import Literal

from pydantic import Field as FieldInfo

from .._models import BaseModel
from .inbound_email_event import InboundEmailEvent
from .send_destination_type import SendDestinationType

__all__ = ["SendWebhookEvent", "GoogleDriveOutput", "Metadata", "S3Output", "WebhookOutput"]


class GoogleDriveOutput(BaseModel):
    """Metadata returned when a Send function delivers to Google Drive."""

    file_name: str = FieldInfo(alias="fileName")
    """Name of the file created in Google Drive."""

    folder_id: str = FieldInfo(alias="folderID")
    """ID of the Google Drive folder the file was placed in."""


class Metadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class S3Output(BaseModel):
    """Metadata returned when a Send function delivers to an S3 bucket."""

    bucket_name: str = FieldInfo(alias="bucketName")
    """Name of the S3 bucket the payload was written to."""

    key: str
    """Object key under which the payload was stored."""


class WebhookOutput(BaseModel):
    """Metadata returned when a Send function delivers to a webhook."""

    http_response_body: str = FieldInfo(alias="httpResponseBody")
    """Raw HTTP response body returned by the webhook endpoint."""

    http_status_code: int = FieldInfo(alias="httpStatusCode")
    """HTTP status code returned by the webhook endpoint."""


class SendWebhookEvent(BaseModel):
    delivery_status: Literal["success", "skip"] = FieldInfo(alias="deliveryStatus")
    """Outcome of a Send function's delivery attempt."""

    destination_type: SendDestinationType = FieldInfo(alias="destinationType")
    """Destination type for a Send function."""

    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    function_id: str = FieldInfo(alias="functionID")
    """Unique identifier of function that this event is associated with."""

    function_name: str = FieldInfo(alias="functionName")
    """Unique name of function that this event is associated with."""

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    call_id: Optional[str] = FieldInfo(alias="callID", default=None)
    """Unique identifier of workflow call that this event is associated with."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    delivered_content: Optional[object] = FieldInfo(alias="deliveredContent", default=None)
    """
    The full protocol event JSON that was delivered — identical to what subscription
    publish would deliver for the same event. For ad-hoc calls with a JSON file
    input, contains the raw input JSON. For ad-hoc calls with a binary file input,
    contains {"s3URL": "<presigned-url>"}.
    """

    event_type: Optional[Literal["send"]] = FieldInfo(alias="eventType", default=None)

    function_call_id: Optional[str] = FieldInfo(alias="functionCallID", default=None)
    """Unique identifier of function call that this event is associated with."""

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    function_version_num: Optional[int] = FieldInfo(alias="functionVersionNum", default=None)
    """Version number of function that this event is associated with."""

    google_drive_output: Optional[GoogleDriveOutput] = FieldInfo(alias="googleDriveOutput", default=None)
    """Metadata returned when a Send function delivers to Google Drive."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    metadata: Optional[Metadata] = None

    s3_output: Optional[S3Output] = FieldInfo(alias="s3Output", default=None)
    """Metadata returned when a Send function delivers to an S3 bucket."""

    webhook_output: Optional[WebhookOutput] = FieldInfo(alias="webhookOutput", default=None)
    """Metadata returned when a Send function delivers to a webhook."""

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of workflow that this event is associated with."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of workflow that this event is associated with."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of workflow that this event is associated with."""
