# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Optional
from datetime import datetime
from typing_extensions import Literal

from pydantic import Field as FieldInfo

from .._models import BaseModel
from .inbound_email_event import InboundEmailEvent

__all__ = ["SplitItemWebhookEvent", "Metadata", "PrintPageOutput", "SemanticPageOutput"]


class Metadata(BaseModel):
    duration_function_to_event_seconds: Optional[float] = FieldInfo(
        alias="durationFunctionToEventSeconds", default=None
    )


class PrintPageOutput(BaseModel):
    collection_reference_id: Optional[str] = FieldInfo(alias="collectionReferenceID", default=None)

    item_count: Optional[int] = FieldInfo(alias="itemCount", default=None)

    item_offset: Optional[int] = FieldInfo(alias="itemOffset", default=None)

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)


class SemanticPageOutput(BaseModel):
    collection_reference_id: Optional[str] = FieldInfo(alias="collectionReferenceID", default=None)

    item_class: Optional[str] = FieldInfo(alias="itemClass", default=None)

    item_class_count: Optional[int] = FieldInfo(alias="itemClassCount", default=None)

    item_class_offset: Optional[int] = FieldInfo(alias="itemClassOffset", default=None)

    item_count: Optional[int] = FieldInfo(alias="itemCount", default=None)

    item_offset: Optional[int] = FieldInfo(alias="itemOffset", default=None)

    page_count: Optional[int] = FieldInfo(alias="pageCount", default=None)

    page_end: Optional[int] = FieldInfo(alias="pageEnd", default=None)

    page_start: Optional[int] = FieldInfo(alias="pageStart", default=None)

    s3_url: Optional[str] = FieldInfo(alias="s3URL", default=None)


class SplitItemWebhookEvent(BaseModel):
    event_id: str = FieldInfo(alias="eventID")
    """Unique ID generated by bem to identify the event."""

    function_id: str = FieldInfo(alias="functionID")
    """Unique identifier of function that this event is associated with."""

    function_name: str = FieldInfo(alias="functionName")
    """Unique name of function that this event is associated with."""

    output_type: Literal["print_page", "semantic_page"] = FieldInfo(alias="outputType")

    reference_id: str = FieldInfo(alias="referenceID")
    """
    The unique ID you use internally to refer to this data point, propagated from
    the original function input.
    """

    call_id: Optional[str] = FieldInfo(alias="callID", default=None)
    """Unique identifier of workflow call that this event is associated with."""

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """Timestamp indicating when the event was created."""

    event_type: Optional[Literal["split_item"]] = FieldInfo(alias="eventType", default=None)

    function_call_id: Optional[str] = FieldInfo(alias="functionCallID", default=None)
    """Unique identifier of function call that this event is associated with."""

    function_call_try_number: Optional[int] = FieldInfo(alias="functionCallTryNumber", default=None)
    """The attempt number of the function call that created this event. 1 indexed."""

    function_version_num: Optional[int] = FieldInfo(alias="functionVersionNum", default=None)
    """Version number of function that this event is associated with."""

    inbound_email: Optional[InboundEmailEvent] = FieldInfo(alias="inboundEmail", default=None)
    """The inbound email that triggered this event."""

    metadata: Optional[Metadata] = None

    print_page_output: Optional[PrintPageOutput] = FieldInfo(alias="printPageOutput", default=None)

    semantic_page_output: Optional[SemanticPageOutput] = FieldInfo(alias="semanticPageOutput", default=None)

    workflow_id: Optional[str] = FieldInfo(alias="workflowID", default=None)
    """Unique identifier of workflow that this event is associated with."""

    workflow_name: Optional[str] = FieldInfo(alias="workflowName", default=None)
    """Name of workflow that this event is associated with."""

    workflow_version_num: Optional[int] = FieldInfo(alias="workflowVersionNum", default=None)
    """Version number of workflow that this event is associated with."""
